### ISSUE TITLE
Add Go to address 

### ISSUE THREAD

**Issue by zareimz** [exbin/bined-android#1]
Hi Miroslav Hajda
I used exbin hex Editor library in my application
I added it to the go to address function  
codeArea moves to the desired address, but scrolling does not
And after scrolling again, it returns to the previous address

  private void goToPosition(long newPosition) {
        codeArea.revealPosition(new DefaultCodeAreaCaretPosition( newPosition, 0,codeArea.getActiveSection() ));
        codeArea.setCaretPosition( newPosition);
    }
    
    Please help to fix this issue

**Comment by hajdam** [comment]
Hi,
Android variant was under development long time ago. It has unfinished rendering, scrolling, virtual keyboard, settings, operations - basically pretty much everything is not finished :-| I reached some hurdles during development and as there are multiple hex editors for Android / even open source ones, it didn't seem worth to continue.

Maybe you could try / would prefer to use other hex editor? For example: https://github.com/Keidan/HexViewer

**Comment by zareimz** [comment]
The code https://github.com/Keidan/HexViewer is written very complicated
and heavy, but I easily used your code, I added new features to it, but
because the coreara source is not available and its jar file was used.  I
can't fix a small bug, this program is suitable for me, I used it in a
bigger project where bin files related to car computer dumps are managed
and edited.

**Comment by hajdam** [comment]
Nice to hear it is at least somewhat useful to someone.

I updated android app to use libraries from maven instead so you can get sources from maven or from source repositories:
https://github.com/exbin/bined-lib-java/tree/master/modules/bined-core
https://github.com/exbin/exbin-auxiliary-java/tree/master/modules/binary_data

**Comment by hajdam** [comment]
Fixed some scrolling issue, but I'm not sure if it will help you with your problem.
Also I believe in normal situation codeArea.setCaretPosition(...) should already scroll to reveal caret (cursor)...
Still lot of issues to fix if I'll have time / ability to do so...

**Comment by hajdam** [comment]
Released app version 0.2.1 which has basic go to address functionality.
