### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [exbin/bined-android#11]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/8080423002#L351

you tagged https://github.com/exbin/bined-android/tree/0.2.2 from https://github.com/exbin/bined-android/commit/721c5f0cdcd500b313ddd12e1642761a649c5f67

but your APK was built from the tree at 3722d5d28a954d85d73277531ab429bed8b4f71f with uncommited changes I guess?

we understand you need to test your commits, but when you are ready to release, please, update versionName and Code, tag a release, THEN build from the tagged commit and upload that APK, not a random APK you had around.

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c53f26c59d35ee850517da43575278af4cf66aae

**Comment by hajdam** [comment]
Hi.
Your guess was correct - I did build with local version change for internal testing.
Sorry about that - apk replaced.
Best regards,
HajdaM

**Comment by licaon-kter** [comment]
confirmed, thanks
