### ISSUE TITLE
Storage permission not granted

### ISSUE THREAD

**Issue by woheller69** [exbin/bined-android#2]
App shows toast "Storage permission not granted" even if I grant the permission manually. Even with all files access permission.

Android 12

**Comment by hajdam** [comment]
I believe it should help to restart the app - exit and or close in task manager and start it again after permission change.
It reads permission once at start, so it's a bug - well app is pretty much early access at this point...

You can try current development version which uses different file access method / dialog:
https://bined.exbin.org/download/?f=bined-android-0.2.1-SNAPSHOT.apk

**Comment by woheller69** [comment]
Thanks, this works.  The permission was not requested either, but I guess this will be added in future, too.
Would be nice to have it on F-Droid.

**Comment by hajdam** [comment]
Released app version 0.2.1 which uses different method to open files.
Permission is probably not needed at this time / doesn't have to be allowed, but it's preserved for now.
