### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [exbin/bined-android#8]
Hey 👋 I am a newbie contributor and I would like to offer to create a documentation task - setting up code of conduct from scratch for the users of bined-android repo. Let me know if it is okay. This is a attempt to make a small contribution as a part of hacktoberfest.

**Comment by hajdam** [comment]
Hi, I don't believe project of this size would need or even benefit from code of conduct, not even for far future. I recommend to offer this instead to other hacktoberfest marked projects with managerial structure which would benefit from such declaration.

**Comment by KiranBaliga** [comment]
Understood, Thank for your response! 💫✨
